# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
  const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
  const response = await fetch(url);
  const users = await response.json();
  console.log(users)
  return users;
}
getUser(-1)
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
No, this function is not safe. This is because it is missing an error handler. A `try` and `catch` block could be used here to make the code efficent and safe or errors. 

# Teacher Feedback
Score: 0/3